from typing import List, Tuple, Protocol, Optional

Point = Tuple[float, float]
Stroke = List[Point]  # [(x,y), (x,y), ...]

class IOCR(Protocol):
    def parse_strokes(self, strokes: List[Stroke]) -> List[Tuple[str, int]]:
        """Връща [(име, сума_в_стотинки), ...]"""
        ...

class IRepository(Protocol):
    def init(self) -> None: ...
    def add_page(self, path: str, ts: str) -> int: ...
    def add_entry(self, name: str, amount_st: int, ts: str, page_id: Optional[int]) -> None: ...
    def search_by_name(self, q: str) -> List[Tuple[str, int]]: ...
    def list_entries(self, name: str) -> List[Tuple[str, int, Optional[int]]]: ...
    def sum_for_name(self, name: str) -> int: ...
