name: Quick Check (Python syntax)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '.github/workflows/quick_check.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Syntax check (py_compile) - fail fast
        run: |
          python - <<'PY'
          import pathlib, sys
          bad = False
          for f in pathlib.Path('.').rglob('*.py'):
              try:
                  compile(open(f,'rb').read(), str(f), 'exec')
              except SyntaxError as e:
                  bad = True
                  print(f"\n❌ SyntaxError in {f}:{e.lineno}:{e.offset}")
                  if e.text:
                      print(e.text.rstrip())
                      if e.offset and e.offset>0:
                          print(' '*(e.offset-1)+'^')
          if bad:
              sys.exit(1)
          print('✅ No syntax errors.')
          PY
